x = input("Enter the word  ")
a = x.count("A")
b = x.count("a")
c = x.count("I")
d = x.count("i")
e = x.count("U")
f = x.count("u")
g = x.count("E")
h = x.count("e")
i = x.count("O")
j = x.count("o")
print(a + b + c + d + e + f + g + h + i + j)